name: GeoWave Publish
on: [pull_request, push]
env:
  DEV_RESOURCES_VERSION: 1.7
  MAVEN_OPTS: "-XX:CompressedClassSpaceSize=256m -XX:+UseSerialGC -Xmx2g -XX:MaxMetaspaceSize=512m -Dorg.slf4j.simpleLogger.defaultLogLevel=warn"
jobs:
  publish:
    if: github.repository == 'locationtech/geowave'
    runs-on: ubuntu-18.04
    name: Publish Artifacts and Docs
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GPG_OWNERTRUST: ${{ secrets.GPG_OWNERTRUST }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_SECRET_KEYS: ${{ secrets.GPG_SECRET_KEYS }}
      PYPI_CREDENTIALS: ${{ secrets.PYPI_CREDENTIALS }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: joschi/setup-jdk@v2
      with:
        java-version: '8'  
        architecture: x64  
        
    - name: Cache resources
      uses: actions/cache@v2
      env:
        cache-name: cache-geowave-resources
      with:
        key:  ${{ runner.os }}-Publish
        path: ~/.m2

    - name: Publish Artifacts
      run: ./.utility/publish-artifacts.sh

    - name: Publish Docs
      run: ./.utility/publish-docs.sh

